### ISSUE TITLE
Manual Bluemix deployment error

### ISSUE THREAD

**Issue by icha024** [node-red/node-red-bluemix#9]
Hi,

I've been experiencing problems in creating Node-Red boiler plate on Bluemix (have raised a ticket for it) - so I'm trying to do a manual deployment with this in the mean time instead.

It's failing with error of 'Can not find Node-red module', logs:

2016-03-15T17:19:40.726-0000[DEA/103]OUTStarting app instance (index 0) with guid f2eeaa9c-c331-4e18-8dd3-129af0418a47
2016-03-15T17:19:51.215-0000[App/0]ERRmodule.js:328
2016-03-15T17:19:51.215-0000[App/0]ERR throw err;
2016-03-15T17:19:51.215-0000[App/0]ERR ^
2016-03-15T17:19:51.216-0000[App/0]ERRError: Cannot find module '/home/vcap/app/node_modules/node-red/red.js'
2016-03-15T17:19:51.221-0000[App/0]ERR at Function.Module._resolveFilename (module.js:326:15)
2016-03-15T17:19:51.222-0000[App/0]ERR at Function.Module.runMain (module.js:442:10)
2016-03-15T17:19:51.222-0000[App/0]ERR at Function.Module._load (module.js:277:25)
2016-03-15T17:19:51.222-0000[App/0]ERR at startup (node.js:136:18)
2016-03-15T17:19:51.223-0000[App/0]OUT
2016-03-15T17:19:51.223-0000[App/0]ERR at node.js:966:3
2016-03-15T17:19:51.396-0000[DEA/103]ERRInstance (index 0) failed to start accepting connections
2016-03-15T17:19:51.423-0000[API/1]OUTApp instance exited with guid f2eeaa9c-c331-4e18-8dd3-129af0418a47 payload: {"cc_partition"=>"default", "droplet"=>"f2eeaa9c-c331-4e18-8dd3-129af0418a47", "version"=>"cb3061b2-27ad-4719-aab6-d4783709d6ca", "instance"=>"de4fdb8b28514b8d88d68f542de09bda", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1458062391}

**Comment by knolleary** [comment]
Hi,

I assume you followed the instructions here: https://github.com/node-red/node-red-bluemix/blob/master/README.md#deploying-node-red-into-bluemix

Do you have the staging logs for your app - that will show what actually got installed and hopefully why it doesn't appear to have installed the node-red module.

As an alternative approach, you could use the Deploy To Bluemix enabled repository here: https://github.com/node-red/node-red-bluemix-starter

**Comment by icha024** [comment]
Hey Nick

Thanks for the link, I was using the instructions from the first link's readme.md. I'll also take a look at the bluemix-starter pack

After a fresh redeploy just now, it got further but with a different error - i think this one might be Bluemix related (?)

Logs:
```
2016-03-16T11:47:27.34+0000 [API/1]      OUT Updated app with guid f2eeaa9c-c331-4e18-8dd3-129af0418a47 ({"state"=>"STOPPED"})
2016-03-16T11:47:30.13+0000 [DEA/30]     OUT Got staging request for app with id f2eeaa9c-c331-4e18-8dd3-129af0418a47
2016-03-16T11:47:38.68+0000 [API/2]      OUT Updated app with guid f2eeaa9c-c331-4e18-8dd3-129af0418a47 ({"state"=>"STARTED"})
2016-03-16T11:47:38.98+0000 [STG/30]     OUT -----> Downloaded app package (3.9M)
2016-03-16T11:47:39.27+0000 [STG/30]     OUT -----> Downloaded app buildpack cache (3.6M)
2016-03-16T11:47:40.30+0000 [STG/0]      OUT 
2016-03-16T11:47:40.30+0000 [STG/0]      OUT -----> IBM SDK for Node.js Buildpack v3.1-20160222-1123
2016-03-16T11:47:40.30+0000 [STG/0]      OUT        Based on Cloud Foundry Node.js Buildpack v1.5.4
2016-03-16T11:47:40.31+0000 [STG/0]      OUT -----> Creating runtime environment
2016-03-16T11:47:40.32+0000 [STG/0]      OUT        NPM_CONFIG_LOGLEVEL=error
2016-03-16T11:47:40.32+0000 [STG/0]      OUT        NPM_CONFIG_PRODUCTION=true
2016-03-16T11:47:40.32+0000 [STG/0]      OUT        NODE_ENV=production
2016-03-16T11:47:40.32+0000 [STG/0]      OUT        NODE_MODULES_CACHE=true
2016-03-16T11:47:40.33+0000 [STG/0]      OUT -----> Installing binaries
2016-03-16T11:47:40.35+0000 [STG/0]      OUT        engines.node (package.json):  unspecified
2016-03-16T11:47:40.35+0000 [STG/0]      OUT        engines.npm (package.json):   unspecified (use default)
2016-03-16T11:47:40.35+0000 [STG/0]      OUT        Resolving node version (latest stable) via 'node-version-resolver'
2016-03-16T11:47:40.56+0000 [STG/0]      OUT        Installing IBM SDK for Node.js (4.3.0) from cache
2016-03-16T11:47:41.44+0000 [STG/0]      OUT        Using default npm version: 2.14.12
2016-03-16T11:47:41.69+0000 [STG/0]      OUT -----> Restoring cache
2016-03-16T11:47:41.99+0000 [STG/0]      OUT        Loading 2 from cacheDirectories (default):
2016-03-16T11:47:41.99+0000 [STG/0]      OUT        - node_modules (exists - skipping)
2016-03-16T11:47:41.99+0000 [STG/0]      OUT        - bower_components (not cached - skipping)
2016-03-16T11:47:42.00+0000 [STG/0]      OUT -----> Checking and configuring service extensions before installing dependencies
2016-03-16T11:47:42.16+0000 [STG/0]      OUT -----> Building dependencies
2016-03-16T11:47:42.16+0000 [STG/0]      OUT        Prebuild detected (node_modules already exists)
2016-03-16T11:47:42.16+0000 [STG/0]      OUT        Rebuilding any native modules
2016-03-16T11:47:43.36+0000 [STG/0]      OUT        connect@2.14.1 /tmp/staged/app/node_modules/connect
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        basic-auth-connect@1.0.0 /tmp/staged/app/node_modules/basic-auth-connect
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        bytes@0.2.1 /tmp/staged/app/node_modules/bytes
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        compression@1.0.0 /tmp/staged/app/node_modules/compression
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        compressible@1.0.0 /tmp/staged/app/node_modules/compressible
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        negotiator@0.3.0 /tmp/staged/app/node_modules/negotiator
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        connect-timeout@1.0.0 /tmp/staged/app/node_modules/connect-timeout
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        debug@0.8.1 /tmp/staged/app/node_modules/debug
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        cookie-parser@1.0.1 /tmp/staged/app/node_modules/cookie-parser
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        cookie@0.1.0 /tmp/staged/app/node_modules/cookie
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        cookie-signature@1.0.3 /tmp/staged/app/node_modules/cookie-signature
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        csurf@1.0.0 /tmp/staged/app/node_modules/csurf
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        uid2@0.0.3 /tmp/staged/app/node_modules/uid2
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        errorhandler@1.0.0 /tmp/staged/app/node_modules/errorhandler
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        express-session@1.0.2 /tmp/staged/app/node_modules/express-session
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        buffer-crc32@0.2.1 /tmp/staged/app/node_modules/buffer-crc32
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        debug@0.7.4 /tmp/staged/app/node_modules/express-session/node_modules/debug
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        utils-merge@1.0.0 /tmp/staged/app/node_modules/utils-merge
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        fresh@0.2.2 /tmp/staged/app/node_modules/fresh
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        method-override@1.0.0 /tmp/staged/app/node_modules/method-override
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        methods@1.1.2 /tmp/staged/app/node_modules/methods
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        morgan@1.0.0 /tmp/staged/app/node_modules/morgan
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        multiparty@2.2.0 /tmp/staged/app/node_modules/multiparty
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        readable-stream@1.1.13 /tmp/staged/app/node_modules/readable-stream
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        core-util-is@1.0.2 /tmp/staged/app/node_modules/core-util-is
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        inherits@2.0.1 /tmp/staged/app/node_modules/inherits
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        isarray@0.0.1 /tmp/staged/app/node_modules/isarray
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        string_decoder@0.10.31 /tmp/staged/app/node_modules/string_decoder
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        stream-counter@0.2.0 /tmp/staged/app/node_modules/stream-counter
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        pause@0.0.1 /tmp/staged/app/node_modules/pause
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        qs@0.6.6 /tmp/staged/app/node_modules/qs
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        raw-body@1.1.3 /tmp/staged/app/node_modules/raw-body
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        response-time@1.0.0 /tmp/staged/app/node_modules/response-time
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        serve-index@1.0.1 /tmp/staged/app/node_modules/serve-index
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        batch@0.5.0 /tmp/staged/app/node_modules/batch
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        negotiator@0.4.2 /tmp/staged/app/node_modules/serve-index/node_modules/negotiator
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        serve-static@1.0.2 /tmp/staged/app/node_modules/serve-static
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        send@0.2.0 /tmp/staged/app/node_modules/send
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        mime@1.2.11 /tmp/staged/app/node_modules/mime
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        range-parser@1.0.3 /tmp/staged/app/node_modules/range-parser
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        static-favicon@1.0.0 /tmp/staged/app/node_modules/static-favicon
2016-03-16T11:47:43.37+0000 [STG/0]      OUT        vhost@1.0.0 /tmp/staged/app/node_modules/vhost
2016-03-16T11:47:43.39+0000 [STG/0]      OUT        Installing any new modules (package.json)
2016-03-16T11:47:44.68+0000 [STG/0]      OUT -----> Checking and configuring service extensions after installing dependencies
2016-03-16T11:47:44.83+0000 [STG/0]      OUT -----> Installing App Management
2016-03-16T11:47:44.86+0000 [STG/0]      OUT        WARN: App Management cannot be installed because the start script cannot be found.
2016-03-16T11:47:44.86+0000 [STG/0]      OUT        To install App Management utilities, specify your 'node' start script in 'package.json' or 'Procfile'.
2016-03-16T11:47:44.86+0000 [STG/0]      OUT -----> Caching build
2016-03-16T11:47:44.87+0000 [STG/0]      OUT        Clearing previous node cache
2016-03-16T11:47:44.92+0000 [STG/0]      OUT        Saving 2 cacheDirectories (default):
2016-03-16T11:47:44.92+0000 [STG/0]      OUT        - node_modules
2016-03-16T11:47:45.03+0000 [STG/0]      OUT        - bower_components (nothing to cache)
2016-03-16T11:47:45.29+0000 [STG/0]      OUT -----> Build succeeded!
2016-03-16T11:47:46.03+0000 [STG/0]      OUT        ├── basic-auth-connect@1.0.0
2016-03-16T11:47:46.03+0000 [STG/0]      OUT        ├── batch@0.5.0
2016-03-16T11:47:46.04+0000 [STG/0]      OUT        ├── buffer-crc32@0.2.1
2016-03-16T11:47:46.04+0000 [STG/0]      OUT        ├── bytes@0.2.1
2016-03-16T11:47:46.04+0000 [STG/0]      OUT        ├── compressible@1.0.0
2016-03-16T11:47:46.04+0000 [STG/0]      OUT        ├── compression@1.0.0
2016-03-16T11:47:46.04+0000 [STG/0]      OUT        ├── connect@2.14.1
2016-03-16T11:47:46.04+0000 [STG/0]      OUT        ├── connect-timeout@1.0.0
2016-03-16T11:47:46.04+0000 [STG/0]      OUT        ├── cookie@0.1.0
2016-03-16T11:47:46.04+0000 [STG/0]      OUT        ├── cookie-parser@1.0.1
2016-03-16T11:47:46.04+0000 [STG/0]      OUT        ├── cookie-signature@1.0.3
2016-03-16T11:47:46.04+0000 [STG/0]      OUT        ├── core-util-is@1.0.2
2016-03-16T11:47:46.04+0000 [STG/0]      OUT        ├── csurf@1.0.0
2016-03-16T11:47:46.04+0000 [STG/0]      OUT        ├── debug@0.8.1
2016-03-16T11:47:46.04+0000 [STG/0]      OUT        ├── errorhandler@1.0.0
2016-03-16T11:47:46.04+0000 [STG/0]      OUT        ├── express-session@1.0.2
2016-03-16T11:47:46.04+0000 [STG/0]      OUT        ├── fresh@0.2.2
2016-03-16T11:47:46.04+0000 [STG/0]      OUT        ├── inherits@2.0.1
2016-03-16T11:47:46.04+0000 [STG/0]      OUT        ├── isarray@0.0.1
2016-03-16T11:47:46.04+0000 [STG/0]      OUT        ├── method-override@1.0.0
2016-03-16T11:47:46.04+0000 [STG/0]      OUT        ├── methods@1.1.2
2016-03-16T11:47:46.04+0000 [STG/0]      OUT        ├── mime@1.2.11
2016-03-16T11:47:46.04+0000 [STG/0]      OUT        ├── morgan@1.0.0
2016-03-16T11:47:46.04+0000 [STG/0]      OUT        ├── multiparty@2.2.0
2016-03-16T11:47:46.04+0000 [STG/0]      OUT        ├── negotiator@0.3.0
2016-03-16T11:47:46.04+0000 [STG/0]      OUT        ├── pause@0.0.1
2016-03-16T11:47:46.04+0000 [STG/0]      OUT        ├── qs@0.6.6
2016-03-16T11:47:46.04+0000 [STG/0]      OUT        ├── range-parser@1.0.3
2016-03-16T11:47:46.04+0000 [STG/0]      OUT        ├── raw-body@1.1.3
2016-03-16T11:47:46.04+0000 [STG/0]      OUT        ├── readable-stream@1.1.13
2016-03-16T11:47:46.04+0000 [STG/0]      OUT        ├── response-time@1.0.0
2016-03-16T11:47:46.04+0000 [STG/0]      OUT        ├── send@0.2.0
2016-03-16T11:47:46.04+0000 [STG/0]      OUT        ├── serve-index@1.0.1
2016-03-16T11:47:46.04+0000 [STG/0]      OUT        ├── serve-static@1.0.2
2016-03-16T11:47:46.04+0000 [STG/0]      OUT        ├── static-favicon@1.0.0
2016-03-16T11:47:46.04+0000 [STG/0]      OUT        ├── stream-counter@0.2.0
2016-03-16T11:47:46.04+0000 [STG/0]      OUT        ├── string_decoder@0.10.31
2016-03-16T11:47:46.04+0000 [STG/0]      OUT        ├── uid2@0.0.3
2016-03-16T11:47:46.04+0000 [STG/0]      OUT        ├── utils-merge@1.0.0
2016-03-16T11:47:46.04+0000 [STG/0]      OUT        └── vhost@1.0.0
2016-03-16T11:47:46.06+0000 [STG/0]      ERR 
2016-03-16T11:47:49.42+0000 [STG/30]     OUT -----> Uploading droplet (17M)
2016-03-16T11:47:56.05+0000 [DEA/30]     OUT Starting app instance (index 0) with guid f2eeaa9c-c331-4e18-8dd3-129af0418a47
2016-03-16T11:48:41.59+0000 [DEA/116]    OUT Starting app instance (index 0) with guid f2eeaa9c-c331-4e18-8dd3-129af0418a47
2016-03-16T11:48:53.11+0000 [DEA/116]    ERR Instance (index 0) failed to start accepting connections
2016-03-16T11:48:53.13+0000 [API/2]      OUT App instance exited with guid f2eeaa9c-c331-4e18-8dd3-129af0418a47 payload: {"cc_partition"=>"default", "droplet"=>"f2eeaa9c-c331-4e18-8dd3-129af0418a47", "version"=>"d37db2b1-e2cb-47f4-95e9-730b4f238c09", "instance"=>"9b11024772c24ab3a48ac0a7477e3a0e", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1458128933}
2016-03-16T11:48:53.13+0000 [API/5]      OUT App instance exited with guid f2eeaa9c-c331-4e18-8dd3-129af0418a47 payload: {"cc_partition"=>"default", "droplet"=>"f2eeaa9c-c331-4e18-8dd3-129af0418a47", "version"=>"d37db2b1-e2cb-47f4-95e9-730b4f238c09", "instance"=>"9b11024772c24ab3a48ac0a7477e3a0e", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1458128933}


2016-03-16T11:49:41.49+0000 [DEA/98]     OUT Starting app instance (index 0) with guid f2eeaa9c-c331-4e18-8dd3-129af0418a47
2016-03-16T11:49:53.23+0000 [DEA/98]     ERR Instance (index 0) failed to start accepting connections
2016-03-16T11:49:53.25+0000 [API/4]      OUT App instance exited with guid f2eeaa9c-c331-4e18-8dd3-129af0418a47 payload: {"cc_partition"=>"default", "droplet"=>"f2eeaa9c-c331-4e18-8dd3-129af0418a47", "version"=>"d37db2b1-e2cb-47f4-95e9-730b4f238c09", "instance"=>"4a8c18ef14cd4ff4ab1e6d38df5248ac", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1458128993}
2016-03-16T11:49:53.25+0000 [API/9]      OUT App instance exited with guid f2eeaa9c-c331-4e18-8dd3-129af0418a47 payload: {"cc_partition"=>"default", "droplet"=>"f2eeaa9c-c331-4e18-8dd3-129af0418a47", "version"=>"d37db2b1-e2cb-47f4-95e9-730b4f238c09", "instance"=>"4a8c18ef14cd4ff4ab1e6d38df5248ac", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1458128993}
2016-03-16T11:50:41.80+0000 [DEA/144]    OUT Starting app instance (index 0) with guid f2eeaa9c-c331-4e18-8dd3-129af0418a47
2016-03-16T11:50:53.38+0000 [DEA/144]    ERR Instance (index 0) failed to start accepting connections
2016-03-16T11:50:53.41+0000 [API/7]      OUT App instance exited with guid f2eeaa9c-c331-4e18-8dd3-129af0418a47 payload: {"cc_partition"=>"default", "droplet"=>"f2eeaa9c-c331-4e18-8dd3-129af0418a47", "version"=>"d37db2b1-e2cb-47f4-95e9-730b4f238c09", "instance"=>"a15441089ce642568187dbbf8022e2d6", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1458129053}
2016-03-16T11:50:53.41+0000 [API/1]      OUT App instance exited with guid f2eeaa9c-c331-4e18-8dd3-129af0418a47 payload: {"cc_partition"=>"default", "droplet"=>"f2eeaa9c-c331-4e18-8dd3-129af0418a47", "version"=>"d37db2b1-e2cb-47f4-95e9-730b4f238c09", "instance"=>"a15441089ce642568187dbbf8022e2d6", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1458129053}
```
